---
root: true
extends: airbnb
parser: babel-eslint
env:
  browser: true
rules:
  semi:
    - 2
    - never
  object-curly-spacing:
    - 2
    - always
    - objectsInObjects: false
      arraysInObjects: false
  react/jsx-filename-extension:
    - 2
    - extensions:
      - .js
      - .jsx
  react/prop-types:
    - 0
